name: Deploy and Test
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Replace script URL
        run: |
          sed -i 's|{{ secrets.GOOGLE_SCRIPT_URL }}|${{ secrets.GOOGLE_SCRIPT_URL }}|g' index.html

      - name: Test Google Script URL endpoint
        run: |
          curl -X POST \
          -d "name=John Doe&email=johndoe@example.com&subject=Test&message=This is a test message" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          ${{ secrets.GOOGLE_SCRIPT_URL }}

      - name: Verify response
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Google Script URL is working"
          else
            echo "❌ Failed to connect to Google Script URL"
            exit 1
          fi